### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by kislerdm** [opentofu/setup-opentofu#3]
## Problem

The release artefacts were prepared manually in a local env, this is highly error prone.

## Proposed Solution

Define a release github workflow. See the [one](https://github.com/hashicorp/setup-terraform/blob/main/.github/workflows/release.yml) hashicorp use as an example.

Followup on #2 ([comment](https://github.com/opentofu/setup-opentofu/pull/2#discussion_r1349662800)).

**Comment by Ant0wan** [comment]
@kislerdm Do you still need a hand on this issue ? My pleasure to help on this if needed.

**Comment by kislerdm** [comment]
@Ant0wan Hey Antoine, thank you for your kind offer! Your contribution would be more than welcomed! 

I reckon we shall consider covering the following acceptance criteria for the release workflow:
- It builds all required artifacts
- It does only run if the test workflows succeeded
- It uses CHANGELOG content as a human readable the release description

WDYT?

**Comment by Ant0wan** [comment]
@kislerdm 
- What specific artifacts are required to be uploaded, and where should they be uploaded to?
- Which tool would you prefer to use for generating the changelog? Is the default GitHub changelog not satisfactory for your needs?

Regarding my latest commit, it incorporates the following changes:
- It will now exclusively execute if the test workflows have successfully completed.
- There may have been a misunderstanding, but it appears to address the major tag offset.

**Comment by kislerdm** [comment]
Hey @Ant0wan 

> Which tool would you prefer to use for generating the changelog?

I'm a proponent of the rule "changelings are for humans" (please find [details](https://keepachangelog.com/en/1.0.0/)). WDYT about using the content of the CHANGELOG.md to populate the release notes?
