### ISSUE TITLE
Error: No matching version found - 1.6.2

### ISSUE THREAD

**Issue by piotrekkr** [opentofu/setup-opentofu#46]
Hello. Since two days this action fails to setup opentofu in version 1.6.2. Worked last week and we did not change anything. Tried rerun and fresh run but result is the same and it fails. I've checked opentofu releases page and tags and both exist for `1.6.2`.

![image](https://github.com/user-attachments/assets/77f5bf3d-7e57-4e3f-8222-675015d67a7c)

Is it somehow on GitHub side or this is issue with this action?

**Comment by piotrekkr** [comment]
Seems like this [PR](https://github.com/opentofu/setup-opentofu/pull/44) should fix this weeks ago but with GH action I'm using `v1` and it does not work. Could it be caching on GH side?

**Comment by piotrekkr** [comment]
Tried with `opentofu/setup-opentofu@v1.0.5` on different repo but result is the same.

![image](https://github.com/user-attachments/assets/c58e7a29-b38d-4a5d-84b4-d1756a844eeb)

**Comment by piotrekkr** [comment]
I think I found the culprit. It is this url `https://get.opentofu.org/tofu/api.json` with version list. It is missing `1.6.2`. Contains `1.6.3` tho so I will try it if it will work.

**Comment by piotrekkr** [comment]
I can confirm that using `1.6.3` works. Not sure why `1.6.2` was removed from this `api.json` but it should not be imho.

**Comment by ollevche** [comment]
Thanks for reporting this one @piotrekkr! Feel free to re-open the issue if there is something wrong
